### ISSUE TITLE
update manifest.json

### ISSUE THREAD

**Issue by L-Jovi** [nirsky/figma-plugin-react-template#16]
Thanks for your project which could help me quickly build figma plugin boilerplate :)

I find the little issue from your template `manifest.json` file

```
...
"editorKey": ["figma"]
...
```

already not be recognized by figma editor, and it could be changed to

```
...
  "editorType": [
    "figma",
    "figjam"
  ]
...
```

Would you mind fix the problem, thx for your time :)

**Comment by nirsky** [comment]
Merged your PR https://github.com/nirsky/figma-plugin-react-template/pull/17
thanks!
