### ISSUE TITLE
what's the purpose of code.js and code.ts?

### ISSUE THREAD

**Issue by jessmchang** [nirsky/figma-plugin-react-template#2]
i've been editing the controller.ts file, which has been working fine. i assume controller.ts gets compiled into code.ts and .js in the /dist directory. but what are code.js and code.ts in the /src directory? they don't seem to do anything yet when i delete the files, my plugin breaks.

**Comment by nirsky** [comment]
Hey @jessmchang,  
There aren't code.js or code.ts files in `src` dir.

What we have is:  
* `src/app/index.tsx` -- bundled into --> `dist/ui.js` + `dist.ui.html`
* `src/plugin/controller.ts` --> bundled into --> `dist/code.js`.

If you prefer using different names you can change them at the [webpack](https://github.com/nirsky/figma-plugin-react-template/blob/master/webpack.config.js) file, under `entry`, and at [manifest.json](https://github.com/nirsky/figma-plugin-react-template/blob/master/manifest.json) as well. 


Not sure why you see `code` files in src but if you'll look at the files in this repo you can see it doesn't exist.  
I hope that helps?

**Comment by jessmchang** [comment]
ohh weird. i think some of my files from the figma react plugin persisted somehow. works great now, thanks!
