### ISSUE TITLE
Images not loading from assets folder

### ISSUE THREAD

**Issue by edu81** [nirsky/figma-plugin-react-template#23]
I am trying to use an image from assets folder like:

<img src={require('../assets/logo.svg')} alt="NONE"/>

The plugin UI is always displaying "NONE".

App.tsx is located in "components" folder while images are in "assets" folder, both folders on same level.

Any help here?

**Comment by karutt** [comment]
By writing it as `require('../assets/logo.svg').default`, it worked.

**Comment by arniebradfo** [comment]
add file `./src/types.d.ts`
```ts
declare module '*.svg' {
	const content: any;
	export default content;
}
```

then import logo src like this
```ts 
import logo from './logo.svg';
<img src={logo} />
```

https://stackoverflow.com/a/45887328/5648839

**Comment by nirsky** [comment]
Added built in SVG TS support
https://github.com/nirsky/figma-plugin-react-template/pull/34
