### ISSUE TITLE
cannot import js functions to controller.ts

### ISSUE THREAD

**Issue by kakax114** [nirsky/figma-plugin-react-template#25]
using regular way to import `import { foo } from './func.ts'`, and call `foo()` got

> TypeError: not a function
>     at ./src/plugin/controller.ts (PLUGIN_71_SOURCE:119)
>     at call (native)
>     at __webpack_require__ (PLUGIN_71_SOURCE:20)
>     at <anonymous> (PLUGIN_71_SOURCE:84)
>     at <anonymous> (PLUGIN_71_SOURCE:343)
>     at call (native)
>     at <eval> (PLUGIN_71_SOURCE:346)

**Comment by nirsky** [comment]
I can't reproduce.
Please share some code
