### ISSUE TITLE
need to specify publicPath?

### ISSUE THREAD

**Issue by perchard** [nirsky/figma-plugin-react-template#32]
https://github.com/nirsky/figma-plugin-react-template/blob/6882081e47019d8e7afa46514e3c3182731a1b80/webpack.config.js#L32

I had to also specify publicPath here:

    publicPath: path.resolve(__dirname, 'dist'),

Otherwise got an error in the Desktop version of Figma stating that publicPath auto was not supported by the browser.

**Comment by nirsky** [comment]
I'm unable to reproduce, can you share the error?

**Comment by perchard** [comment]
hmm, i can no longer reproduce! resolving
