### ISSUE TITLE
Having a specific licence would be useful

### ISSUE THREAD

**Issue by robinwhittleton** [nirsky/figma-plugin-react-template#37]
At the moment the codebase is unlicenced, which means that the legal situation for reuse is ambiguous. Would it be possible to attach a specific licence?

It looks like you’ve designed this to be the basis for other repos (as it’s a template) so I’d suggest that [MIT](https://mit-license.org/) is the most suitable here.

**Comment by nirsky** [comment]
done

**Comment by robinwhittleton** [comment]
Thanks!
